Spring:
  application:
    name: account
  datasource:
    name: test
    url: jdbc:mysql://10.14.32.166:3306/account
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
server:
  port: 1005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

mybatis:
  mapper-locations: classpath:mybatis/*.xml

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000