Spring:
  application:
    name: order
  datasource:
    name: test
    url: jdbc:mysql://10.14.32.166:3306/order
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 1003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

mybatis:
  mapper-locations: classpath:mybatis/*.xml