package com.lc.test.common.vo;

import java.math.BigDecimal;

public class TTestVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.name
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.age
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.phone
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private String phone;

    /**
     * 主键
     *
     * isNullAble:0
     */
    private Integer orderId;

    /**
     *
     * isNullAble:0,defaultVal:
     */
    private String orderCode;

    /**
     *
     * isNullAble:0,defaultVal:0.00
     */
    private java.math.BigDecimal orderPrice;

    /**
     *
     * isNullAble:0,defaultVal:0
     */
    private Integer orderNum;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public String getOrderCode() {
        return orderCode;
    }

    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}
