package com.lc.test.user.model;

public class TTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.name
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.age
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.phone
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.id
     *
     * @param id the value for t_test.id
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.name
     *
     * @return the value of t_test.name
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.name
     *
     * @param name the value for t_test.name
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.age
     *
     * @return the value of t_test.age
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.age
     *
     * @param age the value for t_test.age
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.phone
     *
     * @return the value of t_test.phone
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.phone
     *
     * @param phone the value for t_test.phone
     *
     * @mbggenerated Wed Jul 08 16:35:31 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}